project:
  type: website

website:
  title: "Tony's Travels"
  navbar:
    right:
      - text: "Back to main"
        file: index.qmd
      - text: "About this blog"
        file: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css



